#!/usr/bin/env perl

use strict;
use lib './lib';

use Dancer; # why?
use DancerJukebox;

use Data::Dump;
print "config: " . Data::Dump::dump(DancerJukebox->config()) . "\n";
print "DB: " . ref(DancerJukebox->database()) . "\n";
use DancerJukebox::PlayFromQueue;

DancerJukebox::PlayFromQueue->watch_queue;

